### ISSUE TITLE
High idle CPU load

### ISSUE THREAD

**Issue by TomErnst1972** [openappsec/open-appsec-npm#31]
I would like to reopen:
https://github.com/openappsec/open-appsec-npm/issues/27 
and/or
https://github.com/openappsec/openappsec/issues/119

the idle cpu load is still high on bare metal and docker, eating up ressources even on a very potent machine.
![image](https://github.com/user-attachments/assets/b644e382-1f42-4683-b242-ded4434eea3a)

only a small workaround is to reduce the number of nginx workers within the docker image.

**Comment by BrickMyPhone** [comment]
Same problem for me, immediately when turning on the appsec-agent container CPU Usage spikes to 70-80% and stays there even if nothing is doing requests to the NPM.

Added Screenshot down below of the CPU Utilization, you can clearly see when the agent is turned off how the CPU Usage goes down.
![image](https://github.com/user-attachments/assets/8e1254d4-8336-4b14-b551-b61da92ce57b)

**Comment by orianelou** [comment]
Hi @TomErnst1972 and @BrickMyPhone,

Thank you for the detailed information!

After reviewing your setup, it appears that the high CPU usage is related to the transaction handler. Since there is one handler per core (or per nginx process), the CPU load can accumulate even in idle mode, particularly in environments with multiple cores (like the 56-cores environment you shared).

If this issue persists and demand for a solution grows, we will investigate this further.. In the meantime, we’d be happy to support you anyone from the community who researches this.

Best regards,

Oriane
The open-appsec team

**Comment by BrickMyPhone** [comment]
Hello @orianelou thank you for your response, 

regarding my System I have configured my NPM with 4 Cores as I dont need more. 
When starting the appsec-agent Container there is only one HttpTransactionHandler process running, and unfortunately with even only running one of these processes my idle goes to 80% usage. I guees this has another source of origin, rather than being accounted to handler/core or Core-Count.

I dont think this is something the community will be able to find a solution in the close future. I hope the open-appsec team can investigate this bug and find a solution suitable for the users and the community.

**Comment by BrickMyPhone** [comment]
Update from my Side, it looks like I have fixed my problem.
The Origin of my problem came from the k8s-log-file-handler.sh located in  /etc/cp/HttpTransactionHandler/ inside the container.

When debugging the k8s-log-file-handler.sh.dbg and k8s-log-file-handler.sh.log files in /var/log/nano_agent both of them where empty, contrary to the k8s-log-file-handler.sh.err file which was full of errors seen below:

```
tail: cannot open '/var/log/nano_agent/cp-nano-http-transaction-handler.log?' for reading: No such file or directory
tail: no files remaining
tail: cannot open '/var/log/nano_agent/cp-nano-http-transaction-handler.log?' for reading: No such file or directory
tail: no files remaining
```

Further inspecting the the  k8s-log-file-handler.sh file made it clear why this error would happen.
`tail -q -f /var/log/nano_agent/cp-nano-http-transaction-handler.log? >> /proc/1/fd/1`

It seems like the tail -q -f /var/log/nano_agent/cp-nano-http-transaction-handler.log? command in the script is meant to follow the log file for log rotation, but it isnt working as expected, either because the log file is missing or it cant properly follow rotated log files. But the cp-nano-http-transaction-handler.log file existed under /var/log/nano_agent

So you either install logrotate and configure it as needed or we change the k8s-log-file-handler.sh script to work as intended from the get go.

The new k8s-log-file-handler.sh looks something like this: 

`#!/bin/bash

while true; do
    var_is_hybrid_mode="$(grep "Orchestration mode" /etc/cp/conf/agent_details.json | grep "hybrid_mode")"
    var_is_openappsec="$(grep "Tenant ID" /etc/cp/conf/agent_details.json | grep "org_")"

    if [ -z "${var_is_hybrid_mode}" ] && [ -z "${var_is_openappsec}" ]; then
        sleep 5
        continue
    fi

    # Check for log file
    if [ -f "/var/log/nano_agent/cp-nano-http-transaction-handler.log" ]; then
        tail -q -f /var/log/nano_agent/cp-nano-http-transaction-handler.log >> /proc/1/fd/1 &
        wait
    else
        echo "Log file not found, retry in 5 Seconds" >> /proc/1/fd/1
        sleep 5
    fi
done
`

This immediately dropped my CPU Utilization from 80-85% down to the somewhat reasonable idle utilization of 2-10%.
Dont forget to make the new .sh executable with `chmod +x k8s-log-file-handler.sh`
After killing the old process a new one starts immediately, and now executing the logging with the new .sh file.

@orianelou I would be happy if you can let me know if this is somewhat a feasible fix for the CPU high load by possibly testing this

@TomErnst1972 maybe this is the same problem you are facing as I am not able to see from your screenshot what exactly is causing your CPU Usage
